services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - file_storage:/data/files
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - FILE_STORAGE_PATH=${FILE_STORAGE_PATH}
    depends_on:
      - db

  db:
    image: postgres:17.3-alpine3.21
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data:
    name: lasius_db_data
  file_storage:
    name: lasius_file_storage
