ktor:
  application:
    modules:
      - hu.delheves.lasius.ApplicationKt.module
  deployment:
    port: 8080
postgres:
  driverClassName: "org.postgresql.Driver"
  jdbcURL: "jdbc:postgresql://db:5432/${POSTGRES_DB}"
  user: ${POSTGRES_USER}
  password: ${POSTGRES_PASSWORD}
  filePath: ${FILE_STORAGE_PATH}
